import {
    MatDatepickerModule,
    MatSelectModule,
    MatSnackBarModule,
    MatInputModule,
    MatFormFieldModule,
    MatDialogModule,
    MatGridListModule,
    MatCardModule,
    MatMenuModule,
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatSidenavModule,
    MatIconModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatListModule,
    MatAutocompleteModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatStepperModule,
    MatDividerModule,
    MatExpansionModule,
    MatNativeDateModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatTabsModule,
    MatTooltipModule,
    MatTreeModule,
    MAT_DATE_LOCALE,
    

} from '@angular/material';

/** MatPaginator  Internationalization */
import { MatPaginatorIntl } from '@angular/material';
// import { MatPaginatorIntlKo } from './_class/customPager';

import {NgModule} from '@angular/core';

@NgModule({
    imports: [
        MatDatepickerModule,
        MatSelectModule,
        MatSnackBarModule,
        MatInputModule,
        MatFormFieldModule,
        MatDialogModule,
        MatGridListModule,
        MatCardModule,
        MatMenuModule,
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatSidenavModule,
        MatIconModule,
        MatTableModule,
        MatPaginatorModule,
        MatSortModule,
        MatListModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatStepperModule,
        MatDividerModule,
        MatExpansionModule,
        MatNativeDateModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatTabsModule,
        MatTooltipModule,
        MatTreeModule,
        
    ],
    exports: [
        MatDatepickerModule,
        MatSelectModule,
        MatSnackBarModule,
        MatInputModule,
        MatFormFieldModule,
        MatDialogModule,
        MatGridListModule,
        MatCardModule,
        MatMenuModule,
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatSidenavModule,
        MatIconModule,
        MatTableModule,
        MatPaginatorModule,
        MatSortModule,
        MatListModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatButtonToggleModule,
        MatChipsModule,
        MatStepperModule,
        MatDividerModule,
        MatExpansionModule,
        MatNativeDateModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatRadioModule,
        MatRippleModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatTabsModule,
        MatTooltipModule,
        MatTreeModule,
    ],
    providers: [
        // { provide: MatPaginatorIntl, useClass: MatPaginatorIntlKo },
        { provide: MAT_DATE_LOCALE, useValue: 'ko' },
    ],
    
    
})

export class MaterialModule{}